export const SECCIONES_POR_EVENTO: Record<string, any> = {
  boda: {
    label: 'Boda',
    protagonistas: { label: 'Novios', campo1: 'novia', campo2: 'novio' },
    padres: true,
    padrinos: true,
    segunda_sede: true,
    vestimenta: true,
    itinerario: true,
    galeria: true,
    musica: true,
    regalos: true,
    firmas: true,
    hospedaje: true,
    encuesta: true,
  },
  xv_anos: {
    label: 'XV Años',
    protagonistas: { label: 'Festejada', campo1: 'festejada', campo2: 'chambelanes' },
    padres: true,
    padrinos: true,
    chambelanes: true,
    segunda_sede: true,
    vestimenta: true,
    itinerario: true,
    galeria: true,
    musica: true,
    regalos: true,
    firmas: true,
    hospedaje: true,
    encuesta: true,
  },
  bautizo: {
    label: 'Bautizo',
    protagonistas: { label: 'Bebé', campo1: 'bebe', campo2: 'padres' },
    padres: true,
    padrinos: true,
    segunda_sede: true,
    vestimenta: true,
    itinerario: true,
    galeria: true,
    musica: true,
    regalos: true,
    firmas: true,
    hospedaje: false,
    encuesta: false,
  },
  graduacion: {
    label: 'Graduación',
    protagonistas: { label: 'Graduado/a', campo1: 'graduado', campo2: '' },
    padres: true,
    padrinos: false,
    institucion: true,
    career: true,
    segunda_sede: true,
    vestimenta: true,
    itinerario: true,
    galeria: true,
    musica: true,
    regalos: true,
    firmas: true,
    hospedaje: false,
    encuesta: false,
  },
  baby_shower: {
    label: 'Baby Shower',
    protagonistas: { label: 'Futuros Papás', campo1: 'mama', campo2: 'papa' },
    padres: false,
    padrinos: false,
    segunda_sede: false,
    vestimenta: false,
    itinerario: true,
    galeria: true,
    musica: true,
    regalos: true,
    firmas: true,
    hospedaje: false,
    encuesta: false,
  },
};
